-- Lido.js (template) generation history.
--
-- The generated document (`[{"layers": ..., "meta": ...}]`) is stored directly in
-- `document` — the source of truth a design is reopened from. `path` is kept only for
-- a design promoted in from the old file-based storage (nullable; new rows leave it null).

create table if not exists lido_generations (
  -- Sequential row identity, not exposed publicly (`design_key` is). Decoupled from
  -- `design_key` because that slug is generated and used to name the design's uploaded
  -- images (public/lido-generated/<design_key>/...) before this row exists to insert.
  id integer generated always as identity primary key,
  -- The slug this design is publicly known by (GET /v1/lido/generations/<design_key>,
  -- and its uploaded images' object-store path). Generated by new_design_id() before
  -- the row is inserted; kept unique so a caller can safely retry an insert.
  design_key text not null unique,
  template_id integer references lido_templates(id) on delete set null,
  name text not null default '',
  kind text not null default 'post',
  aspect text not null default '1:1',
  prompt text not null default '',
  canvas_size jsonb not null default '{}',
  thumbnail_url text,
  document jsonb not null default '{}',
  path text,
  created_at timestamptz not null default now()
);
create index if not exists lido_generations_created_idx on lido_generations (created_at desc);
