"""`asset.background` / `asset.subject` equivalents for the Lido corpus — §1.4, retargeted.

Lido's `photo` slots (FrameLayer + clipPath) are cover-cropped inside a shape, not
floating cutouts, so they're generated as ordinary opaque photography via
`TextToImage`, not `TransparentImage` — there's no alpha edge to composite here, the
clip path does the cropping. `logo` slots are never regenerated: a logo is supplied by
the brand, not invented (mirrors `assets_provided.logo_asset_id` in the DesignDoc plan).

Generated bytes go straight through `app.storage.assets` (no DB row — that module's
`store_bytes`/`url_for` are pure filesystem/S3 calls) so this has zero dependency on a
DB session, same as the rest of this corpus.
"""

from __future__ import annotations

import uuid

from app.adapters.base import AdapterError
from app.adapters.registry import text_to_image as get_text_to_image
from app.schema.brief import DesignBrief
from app.storage.assets import store_bytes, url_for

from .model import LidoTemplateFile, SlotInfo

NEGATIVE_TEXT = (
    "text, letters, words, numbers, typography, watermark, logo, signature, caption, "
    "ui, frame, border"
)


def _mood_str(brief: DesignBrief) -> str:
    return " ".join(brief.mood) or "clean, professional"


async def _generate(prompt: str, *, width: int, height: int) -> bytes | None:
    try:
        result = await get_text_to_image().generate(
            prompt=prompt, negative_prompt=NEGATIVE_TEXT,
            width=max(64, min(2048, width)), height=max(64, min(2048, height)),
        )
        return result.data
    except AdapterError:
        return None  # degrade gracefully — keep the template's original photo (§0.9)


async def generate_background(brief: DesignBrief, canvas_w: int, canvas_h: int) -> str | None:
    prompt = (
        f"{_mood_str(brief)} {brief.kind} background"
        + (f" for {brief.subject_description}" if brief.subject_description else "")
        + ", empty, uncluttered, no text, no people"
    )
    data = await _generate(prompt, width=canvas_w, height=canvas_h)
    if data is None:
        return None
    blob = store_bytes(None, f"lido-{uuid.uuid4().hex}", data)
    return url_for(blob.storage_key)


async def generate_photo(brief: DesignBrief, slot: SlotInfo, subject_index: int = 0) -> str | None:
    subject = brief.subject_at(subject_index)
    if subject is None:
        return None
    box = slot.box_size or {}
    w, h = int(box.get("width", 800)), int(box.get("height", 800))
    prompt = f"{subject}, {_mood_str(brief)} lighting, professional photography, three-quarter view"
    data = await _generate(prompt, width=w, height=h)
    if data is None:
        return None
    blob = store_bytes(None, f"lido-{uuid.uuid4().hex}", data)
    return url_for(blob.storage_key)


async def generate_lido_assets(brief: DesignBrief, template: LidoTemplateFile) -> dict[str, str]:
    """Returns `{layer_id: new_image_url}` for the background (`"ROOT"`) plus every
    `photo` slot. Never touches `logo` slots — a logo comes from the brand, not a
    generator. Failures (no adapter configured, provider error) are swallowed per-slot:
    a slot just keeps its original stock photo rather than the whole request failing
    (§0.9 "a partial design always beats an error page").
    """
    box = template.layers["ROOT"].props.get("boxSize", {"width": 1024, "height": 1024})
    out: dict[str, str] = {}

    bg_url = await generate_background(brief, int(box.get("width", 1024)), int(box.get("height", 1024)))
    if bg_url:
        out["ROOT"] = bg_url

    photo_index = 0
    for slot in template.meta.slots:
        if slot.role != "photo":
            continue
        url = await generate_photo(brief, slot, subject_index=photo_index)
        photo_index += 1
        if url:
            out[slot.layer_id] = url
    return out
